### ISSUE TITLE
Knative Eventing Configuration Parity

### ISSUE THREAD

**Issue by travis-minke-sap** [kyma-incubator/knative-kafka#112]
The goal is to be able to swap this kafka implementation out for the current eventing-contrib/kafka implementation without have to change the configuration in the cluster (configmaps / secrets / etc.). For instance we have already standardized on their logging configmap and it's watcher.  We have not yet, though, standardized on their Tracing and Observability configuration support and implementation.  Therefore we want to look into what they're doing in this regard and migrate to the same implementation if possible or raise issues if not.  Some investigation required to ramp up on the two approaches.

**Comment by pbochynski** [comment]
Closing all issues as the project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
