### ISSUE TITLE
Kafka Configuration Parity

### ISSUE THREAD

**Issue by travis-minke-sap** [kyma-incubator/knative-kafka#113]
The goal is to be able to swap this kafka implementation out for the current eventing-contrib/kafka implementation without have to change the configuration in the cluster (ConfigMaps / Secrets / etc.). For instance we have already standardized on their logging configmap and it's watcher. 

The current eventing-contrib/kafka implementation has a ConfigMap where the broker information is stored, whereas we have a "Kafka Secret" (and associated controller) with a more decomposed breakdown of username/password.

We need to look into consolidating these two things.  In this case it might be that out implementation is more fully featured and/or secure and we'd want to push knative towards that direction.  First step is to understand the two implementations, consider future requirements, and then come up with an approach between the two implementations.

**Comment by pbochynski** [comment]
Closing all issues as the project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
