### ISSUE TITLE
Add addressable resolver cluster role

### ISSUE THREAD

**Issue by davyodom** [kyma-incubator/knative-kafka#12]
Cluster role for aggregated addressable resolver cluster role must be added for KafkaChannel

See the following for the specific requirement:
https://github.com/knative/eventing/blob/master/docs/spec/channel.md#aggregated-addressable-resolver-clusterrole

**Comment by travis-minke-sap** [comment]
As part of the v0.10 upgrade this missing RBAC configuration has become required, so these changes will be included in that deliverable.  See https://github.com/kyma-incubator/knative-kafka/issues/18

**Comment by travis-minke-sap** [comment]
Closing as part of Issue #18 being merged.
