### ISSUE TITLE
Cloud Events Support

### ISSUE THREAD

**Issue by davyodom** [kyma-incubator/knative-kafka#13]
Cloud Events v0.3 must be supported over the kafka channels inbound HTTP endpoint and outbound http request to subscriber.  The CloudEvents SDK should be evaluated for use https://github.com/cloudevents/sdk-go .  The Knative good_client https://github.com/knative/eventing/blob/master/pkg/kncloudevents/good_client.go should be evaluated for potential benefits on top of the standard.  

Kafka CE bindings were not a part of the v0.3 spec, but were added for 1.0.  There is no hard requirement to begin using this approach now, but it might be convenient when already trying to meet the requirements of not altering the event as it passes through kafka.

Cloud event sent in to the channel must be have the same data and all other CE attributes as the cloud event sent to subscribers (except for tracing header manipulation)

See the following for further reference of conformance requirements addressed in this story (not all requirements are implemented in this story):
https://github.com/knative/eventing/blob/master/docs/spec/channel.md#input
https://github.com/knative/eventing/blob/master/docs/spec/channel.md#output

(5)

**Comment by phamilton** [comment]
Addressed in PR #25
