### ISSUE TITLE
Expose channel metrics

### ISSUE THREAD

**Issue by davyodom** [kyma-incubator/knative-kafka#16]
The recommended list of metrics should be exposed by the Kafka Channel

https://github.com/knative/eventing/blob/master/docs/spec/channel.md#metrics

**Comment by phamilton** [comment]
Some metrics (specifically counters around writing and reading from kafka) were added as part of #57.

However there are additional metrics mentioned in the spec which should be implemented as well, so leaving this open.

**Comment by pbochynski** [comment]
Closing all issues as the project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
