### ISSUE TITLE
Partition based on CE attribute

### ISSUE THREAD

**Issue by davyodom** [kyma-incubator/knative-kafka#17]
The optional CE attribute of 'subject' should be used as a partition key when present to support in order processing of events for a given entity while allowing scale of consumption of events of a given type.  If the optional attribute is not present, random partitioning approaching an even distribution across partitions should be used.  

Previously, a custom kyma field was being used which contained the same semantic context.

**Comment by phamilton** [comment]
Fixed as part of #13
