### ISSUE TITLE
Upgrade to Knative Eventing 0.10

### ISSUE THREAD

**Issue by davyodom** [kyma-incubator/knative-kafka#18]
Upgrade to Knative 0.10 and verify functionality

Does not include all conformance requirements such as Cloud Events support.  Basic runtime capability to send events to channel and support multiple subscriptions should be verified.  

Change docker tag to 0.10 eventing version (makefile)

(5)

**Comment by travis-minke-sap** [comment]
Closing as fixed.   

Note - the docker tag is back to latest as discussed (differs from original intent above).
