### ISSUE TITLE
Channel deployment consolidation

### ISSUE THREAD

**Issue by davyodom** [kyma-incubator/knative-kafka#22]
In current design, each channel gets its own ingress deployment to act with maximum isolation and independence of scale.  This comes with a high resource cost for underutilized or low volume channels.  These deployments should be consolidated to a single deployment ~~per cluster~~ per Kafka authentication instance.  This deployment will be easy to scale horizontally as needed.    

By having a single Channel Deployment/Service per Kafka authentication instance (K8S Secrets) we should be able to keep the refactor manageable while staying aligned with the longer term goals (multi-tenancy, etc.).  This is less granular than "per-cluster" but still achieves efficiency gains from aggregating Channel Deployments.

**Comment by travis-minke-sap** [comment]
Finished - Closing
