### ISSUE TITLE
Upgrade librdkafka and confluent-kafka-go dependencies

### ISSUE THREAD

**Issue by phamilton** [kyma-incubator/knative-kafka#26]
There have been a number of bugfixes which would be nice to pull in from the newer versions of librdkafka and confluent-kafka-go.  As of today the latest version available is 1.3.0.

**Comment by pbochynski** [comment]
Closing all issues as the project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
