### ISSUE TITLE
Add endpoint Checks For Channel Service READY Status

### ISSUE THREAD

**Issue by travis-minke-sap** [kyma-incubator/knative-kafka#47]
The newly consolidated Channel architecture has improved the granularity of the Status checks to better align with the Knative standard (includes Topic status, etc) but is still missing the actual K8S  "endpoint" checks for the Channel Service.  This issue is expected to address that gap.

**Comment by pbochynski** [comment]
Closing all issues as the project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
