### ISSUE TITLE
Allow Producer / Consumer Settings To Be Configured Dynamically

### ISSUE THREAD

**Issue by phamilton** [kyma-incubator/knative-kafka#65]
Currently the librdkafka settings for the both the consumer and the producer are hardcoded as constants in the common component and are set to our particular needs.  We need to come up with a way to allow the user to specify the consumer and producer configuration options they want.

**Comment by pbochynski** [comment]
Closing all issues as the project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
