### ISSUE TITLE
Add Update/Override Capability To Channel / Dispatcher Reconcilers

### ISSUE THREAD

**Issue by travis-minke-sap** [kyma-incubator/knative-kafka#8]
The current reconciliation logic of the Channel / Dispatcher components (Services, Deployments) assumes that if the artifact exists then it is correct.  This means that a user could manually change these artifacts such that they are incorrect or inconsistent with the owning KafkaChannel and Knative Subscription instances.  Therefore, we would like to add some logic to compare the relevant / important fields in the labels/spec/etc and forcibly update/revert any such changes back to their expected/consistent values.  The exact list of fields to be enforced is not yet defined and should be reviewed prior to implementation.  The goal is to focus only on items that are owned by, or derived from, the owning KafkaChannel and Subscription.

### Notes...

Immediately prior to open sourcing this project, some logic to do this was added to the Channel and Dispatcher reconcilers.  This implementation was too aggressive however and simply overwrite any/all changes to the Service/Deployments labels and spec sections.  Further, there wasn't any allowance made for the fact the K8S will add things to the spec, resulting in unnecessary updates during reconciliation.  That implementation should be referenced when beginning this work, but essentially rewritten for the more specific use case described above.

**Comment by pbochynski** [comment]
Closing all issues as project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
