### ISSUE TITLE
Convert to use ko build/deployment

### ISSUE THREAD

**Issue by phamilton** [kyma-incubator/knative-kafka#83]
Currently we are utilizing a helm chart for deployment purposes.  As the rest of knative-eventing is utilizing ko we should switch over to that model for deployment.

Notes:
- Look at knative-eventing and see how they use ko, follow their lead
- For now we want to continue to use prow, and so need to keep makefile and the targets in the makefile and the kyma-incubator repo
- One potentially tricky thing is that knative-kafka components depend on a C library (librdkafka).  Likely this will require us to build a custom base image to be used in ko.  Though we should investigate if there are any other alternative approaches.
- Update documentation to explain how to use ko.  Specify that helm is deprecated.
- ko training for the team

See https://github.com/google/ko for documentation.

For now we will leave the helm chart in place and will decide later where to move it to.

**Comment by pbochynski** [comment]
Closing all issues as the project is going to be archived. If it is still valid create a new issue in https://github.com/knative-sandbox/eventing-kafka
