### ISSUE TITLE
Dispatcher - Graceful Shutdown

### ISSUE THREAD

**Issue by sbgreene1307** [kyma-incubator/knative-kafka#86]
The dispatcher's KAFKA_OFFSET_COMMIT_MESSAGE_COUNT and KAFKA_OFFSET_COMMIT_DURATION_MILLIS env vars determine when to commit the offset, but when the dispatcher terminates, there is a chance that the offset has not been committed yet. 

The dispatcher should commit the offset when a value is sent to the stopChannel.

**Comment by travis-minke-sap** [comment]
Now performs a final offset commit on shutdown.
